#!/usr/bin/perl

##*****************************************************************************
##
##  Project Name:	AA LocProcess
##     File Name:	AAExtractNib
##        Author:	Stanley Au-Yeung
##          Date:	Monday, November 21, 2005
##
##   Description:	What it does...
##
##                       Copyright Apple Computer Inc.
##                            All rights reserved.
##
##*****************************************************************************
##                       A U T H O R   I D E N T I T Y
##*****************************************************************************
##
##	Initials	Name
##	--------	-----------------------------------------------
##	SA			Stanley Au-Yeung (stanleyauyeung@asia.apple.com)
##
##*****************************************************************************
##                      R E V I S I O N   H I S T O R Y
##*****************************************************************************
##
##	Date		Time	Author	Description
##	--------	-----	------	---------------------------------------------
##	11/22/05	12:00	SA		Original version
##
##*****************************************************************************

#---------------------------------------------------------------------------------------------
#	Modules Used
#---------------------------------------------------------------------------------------------

use File::Path;
use File::Find;
use File::stat;
use File::Spec;
use File::Copy;




#=============================================================================================
#	Main Program
#=============================================================================================

# set version string
$version = "1.0.0";


#---------------------------------------------------------------------------------------------
#
#---------------------------------------------------------------------------------------------

#deals with bad arguments
if (@ARGV == 0)
{
	print "\n### ERROR: Found no parameter.\n";
	&UsageLine();
	exit (2);
}

if (@ARGV > 1)
{
	print "\n### ERROR: Found too many parameters.\n";
	&UsageLine();
	exit (2);
}

# deals with arguments
foreach $item (@ARGV)
{
	if ($item eq "-help")
	{
		&Usage();
		exit (2);
	}

	if ($item eq "-h")
	{
		&Usage();
		exit (2);
	}

	$nibFile = $item;
}

if (-e $nibFile)
{
	$nibFile =~ s|/?$|/|;	# has to end with one slash
	$nibFile =~ m/(.*)\//;	# take out the last /
	$nibFile = $1;
	
	$nibFile =~ m/(.*)\.(.*)/;
	$outFile = $1 . ".txt";	

	`nibtool -a "$nibFile" > "$outFile"`;
}
else
{
	print "ERROR: specified path '$nibFile' doesn't exist.\n";
	exit(1);
}

exit(0);


#---------------------------------------------------------------------------------------------
#	UsageLine
#---------------------------------------------------------------------------------------------

sub UsageLine
{
	print "\nUsage: AAExtractNib <NIB File>\n\n";
}


#---------------------------------------------------------------------------------------------
#	Usage
#---------------------------------------------------------------------------------------------

sub Usage
{
	print "\n";
	print "AAExtractNib [Version $version]\n";
	&UsageLine();
	print "  -help or -h   Display this help.\n";
	print "\n";

	exit(2);
}


#=============================================================================================
#									E N D   O F   F I L E
#=============================================================================================

